import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import BackgroundLayers from "./_components/BackgroundLayers";

export const metadata: Metadata = {
  title: "Dimtech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <BackgroundLayers>{children}</BackgroundLayers>
        </Providers>
      </body>
    </html>
  );
}
